apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: flux-system
  install:
    createNamespace: true
  values:
    domain: "bb.local"
    networkPolicies:
      enabled: false
    istio:
      enabled: trie

    loki: { enabled: true }
    promtail: { enabled: true }
    grafana: { enabled: true }
    prometheus: { enabled: true }
    keycloak: { enabled: true }
    gitlab: { enabled: false }
    harbor: { enabled: false }
    neuvector: { enabled: false }