apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: flux-system
  install:
    createNamespace: true
  values:
    domain: "bb.local"
    networkPolicies:
      enabled: false
    addons:
      kyverno:
        enabled: false
      kyvernoPolicies:
        enabled: false
        
      istio:
        enabled: true
      prometheus:
        enabled: true
      grafana:
        enabled: true
      loki:
        enabled: true
      promtail:
        enabled: true
      keycloak:
        enabled: true
      harbor:
        enabled: false
      gitlab:
        enabled: false
      neuvector:
        enabled: false